name:                dockercleaner
version:             0.1.0.0
github:              "example_user/dockercleaner"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <example_user/dockercleaner#readme>

dependencies:
- base >= 4.7 && < 5
- language-docker >= 10.4.2 && < 11
- ShellCheck >= 0.7.2 && < 0.8
- text >= 1.2.4.1 && < 2
- aeson >= 1.5.6.0 && < 2
- parsec >= 3.1.14.0 && < 4
- directory >= 1.3.6.0 && < 2
- cassava >= 0.5.2.0 && < 0.6
- bytestring >= 0.10.12.0 && < 0.11
- vector >= 0.12.3.1 && < 0.13
- containers >= 0.6.5.1 && < 0.7
- process >= 1.6.13.2 && < 2
- random >=1.2.0 && <2
- QuickCheck >= 2.14.2 && < 3
- splitmix >= 0.1.0.4 && < 0.2
- hashable >= 1.3.0.0 && < 2
- mtl >= 2.2 && < 3
- cryptonite >= 0.29 && < 1
- memory >= 0.15.0 && < 1
- optparse-applicative >= 0.16.0.0 && < 0.18
- split

library:
  source-dirs: src

executables:
  dockercleaner:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dockercleaner

tests:
  dockercleaner-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dockercleaner
    - QuickCheck >= 2.14.2 && < 3
